INSERT INTO Fixtures VALUES (1,'England','South Africa','The Oval','May 30 2019','The Oval');
INSERT INTO Fixtures VALUES (2,'Pakistan','West Indies','Nottingham','May 31 2019','Nottingham');
INSERT INTO Fixtures VALUES (3,'Sri Lanka','New Zealand','Cardiff','June 1 2019','Cardiff');
INSERT INTO Fixtures VALUES (4,'Afghanistan','Australia','Bristol','June 1 2019','Bristol');
INSERT INTO Fixtures VALUES (5,'Bangladesh','South Africa','The Oval','June 2 2019','The Oval');
INSERT INTO Fixtures VALUES (6,'Pakistan','England','Nottingham','June 3 2019','Nottingham');
INSERT INTO Fixtures VALUES (7,'Sri Lanka','Afghanistan','Cardiff','June 4 2019','Cardiff');
INSERT INTO Fixtures VALUES (8,'South Africa','India','Southampton','June 5 2019','Southampton');
INSERT INTO Fixtures VALUES (9,'Bangladesh','New Zealand','The Oval','June 5 2019','The Oval');
INSERT INTO Fixtures VALUES (10,'Australia','West Indies','Nottingham','June 6 2019','Nottingham');
INSERT INTO Fixtures VALUES (11,'Pakiatan','Sri Lanka','Bristol','June 7 2019','Bristol''The Oval');
INSERT INTO Fixtures VALUES (12,'England','Bangladesh','Cardiff','June 8 2019','Cardiff');
INSERT INTO Fixtures VALUES (13,'Afghanistan','New Zealand','Taunton','June 8 2019','Taunton');
INSERT INTO Fixtures VALUES (14,'India','Australia','The Oval','June 9 2019','The Oval');
INSERT INTO Fixtures VALUES (15,'South Africa','West Indies','Southampton','June 10 2019','Southampton');
INSERT INTO Fixtures VALUES (16,'Bangladesh','Sri Lanka','Bristol','June 11 2019','Bristol');
INSERT INTO Fixtures VALUES (17,'Australia','Pakistan','Taunton','June 12 2019','Taunton');
INSERT INTO Fixtures VALUES (18,'India','New Zealand','Nottingham','June 13 2019','Nottingham');
INSERT INTO Fixtures VALUES (19,'West Indies','England','Southampton','June 14 2019','Southampton');
INSERT INTO Fixtures VALUES (20,'Australia','Sri Lanka','The Oval','June 15 2019','The Oval');
INSERT INTO Fixtures VALUES (21,'Afghanistan','South Africa','Cardiff','June 15 2019','Cardiff');
INSERT INTO Fixtures VALUES (22,'India','Pakistan','Manchester','June 16 2019','Manchester');
INSERT INTO Fixtures VALUES (23,'West Indies','Bangladesh','Taunton','June 17 2019','Taunton');
INSERT INTO Fixtures VALUES (24,'England','Afghanistan','Manchester','June 18 2019','Manchester');
INSERT INTO Fixtures VALUES (25,'South Africa','New Zealand','Birmingham','June 19 2019','Birmingham');
INSERT INTO Fixtures VALUES (26,'Australia','Bangladesh','Nottingham','June 20 2019','Nottingham');
INSERT INTO Fixtures VALUES (27,'Sri Lanka', 'England','Leeds','June 21 2019','Leeds');
INSERT INTO Fixtures VALUES (28,'India','Afghanistan','Southampton','June 22 2019','Southampton');
INSERT INTO Fixtures VALUES (29,'New Zealand','West Indies','Manchester','June 22 2019','Manchester');
INSERT INTO Fixtures VALUES (30,'Pakistan','South Africa',"Lord's",'June 23 2019',"Lord's");
INSERT INTO Fixtures VALUES (31,'Bangladesh','Afghanistan','Southampton','June 24 2019','Southampton');
INSERT INTO Fixtures VALUES (32,'Australia','England',"Lord's",'June 25 2019',"Lord's");
INSERT INTO Fixtures VALUES (33,'New Zealand','Pakistan','Birmingham','June 26 2019','Birmingham');
INSERT INTO Fixtures VALUES (34,'India','West Indies','Manchester','June 27 2019','Manchester');
INSERT INTO Fixtures VALUES (35,'Sri Lanka','South Africa','Chester-le-Street','June 28 2019','Chester-le-Street');
INSERT INTO Fixtures VALUES (36,'Afghanistan','Pakistan','Leeds','June 29 2019','Leeds');
INSERT INTO Fixtures VALUES (37,'Australia','New Zealand',"Lord's",'June 29 2019',"Lord's");
INSERT INTO Fixtures VALUES (38,'England','India','Birmingham','June 30 2019','Birmingham');
INSERT INTO Fixtures VALUES (39,'Sri Lanka','West Indies','Chester-le-Street','July 1 2019','Chester-le-Street');
INSERT INTO Fixtures VALUES (40,'India','Bangladesh','Birmingham','July 2 2019','Birmingham');
INSERT INTO Fixtures VALUES (41,'England','New Zealand','Chester-le-Street','July 3 2019','Chester-le-Street');
INSERT INTO Fixtures VALUES (42,'West Indies','Afghanistan','Leeds','July 4 2019','Leeds');
INSERT INTO Fixtures VALUES (43,'Pakistan','Bangladesh',"Lord's",'July 5 2019',"Lord's");
INSERT INTO Fixtures VALUES (44,'Sri Lanka','India','Leeds','July 6 2019','Leeds');
INSERT INTO Fixtures VALUES (45,'South Africa','Australia','Manchester','July 6 2019','Manchester');
INSERT INTO Fixtures VALUES (46,'New Zealand','India','Manchester','July 9 2019','Manchester');
INSERT INTO Fixtures VALUES (47,'Australia','England','Birmingham','July 11 2019','Birmingham');
INSERT INTO Fixtures VALUES (48,'New Zealand','England',"Lord's",'July 14 2019',"Lord's");