SET FOREIGN_KEY_CHECKS = 0;

INSERT INTO `Ground_Matches` VALUES ('The Oval',1);
INSERT INTO `Ground_Matches` VALUES ('Trent Bridge',2);
INSERT INTO `Ground_Matches` VALUES ('Cardiff Wales Stadium',3);
INSERT INTO `Ground_Matches` VALUES ('Bristol County Ground',4);
INSERT INTO `Ground_Matches` VALUES ('The Oval',5);
INSERT INTO `Ground_Matches` VALUES ('Trent Bridge',6);
INSERT INTO `Ground_Matches` VALUES ('Cardiff Wales Stadium',7);
INSERT INTO `Ground_Matches` VALUES ('Rose Bowl',8);
INSERT INTO `Ground_Matches` VALUES ('The Oval',9);
INSERT INTO `Ground_Matches` VALUES ('Trent Bridge',10);
INSERT INTO `Ground_Matches` VALUES ('Bristol County Ground',11);
INSERT INTO `Ground_Matches` VALUES ('Cardiff Wales Stadium',12);
INSERT INTO `Ground_Matches` VALUES ('County Ground',13);
INSERT INTO `Ground_Matches` VALUES ('The Oval',14);
INSERT INTO `Ground_Matches` VALUES ('Rose Bowl',15);
INSERT INTO `Ground_Matches` VALUES ('Bristol County Ground',16);
INSERT INTO `Ground_Matches` VALUES ('County Ground',17);
INSERT INTO `Ground_Matches` VALUES ('Trent Bridge',18);
INSERT INTO `Ground_Matches` VALUES ('Rose Bowl',19);
INSERT INTO `Ground_Matches` VALUES ('The Oval',20);
INSERT INTO `Ground_Matches` VALUES ('Cardiff Wales Stadium',21);
INSERT INTO `Ground_Matches` VALUES ('Old Trafford',22);
INSERT INTO `Ground_Matches` VALUES ('County Ground',23);
INSERT INTO `Ground_Matches` VALUES ('Old Trafford',24);
INSERT INTO `Ground_Matches` VALUES ('Edgbaston',25);
INSERT INTO `Ground_Matches` VALUES ('Trent Bridge',26);
INSERT INTO `Ground_Matches` VALUES ('Yorkshire',27);
INSERT INTO `Ground_Matches` VALUES ('Rose Bowl',28);
INSERT INTO `Ground_Matches` VALUES ('Old Trafford',29);
INSERT INTO `Ground_Matches` VALUES ("Lord's",30);
INSERT INTO `Ground_Matches` VALUES ('Rose Bowl',31);
INSERT INTO `Ground_Matches` VALUES ("Lord's",32);
INSERT INTO `Ground_Matches` VALUES ('Edgbaston',33);
INSERT INTO `Ground_Matches` VALUES ('Old Trafford',34);
INSERT INTO `Ground_Matches` VALUES ('Riverside Ground',35);
INSERT INTO `Ground_Matches` VALUES ('Yorkshire',36);
INSERT INTO `Ground_Matches` VALUES ("Lord's",37);
INSERT INTO `Ground_Matches` VALUES ('Edgbaston',38);
INSERT INTO `Ground_Matches` VALUES ('Riverside Ground',39);
INSERT INTO `Ground_Matches` VALUES ('Edgbaston',40);
INSERT INTO `Ground_Matches` VALUES ('Riverside Ground',41);
INSERT INTO `Ground_Matches` VALUES ('Yorkshire',42);
INSERT INTO `Ground_Matches` VALUES ("Lord's",43);
INSERT INTO `Ground_Matches` VALUES ('Yorkshire',44);
INSERT INTO `Ground_Matches` VALUES ('Old Trafford',45);
INSERT INTO `Ground_Matches` VALUES ('Old Trafford',46);
INSERT INTO `Ground_Matches` VALUES ('Edgbaston',47);
INSERT INTO `Ground_Matches` VALUES ("Lord's",48);