SET FOREIGN_KEY_CHECKS = 0;
INSERT INTO Grounds VALUES ("Lord's",'England','London');
INSERT INTO Grounds VALUES ('Old Trafford','England','Manchester');
INSERT INTO Grounds VALUES ('Bristol County Ground','England','Bristol');
INSERT INTO Grounds VALUES ('Riverside Ground','England', 'Chester-Le-Street');
INSERT INTO Grounds VALUES ('Trent Bridge','England','Nottingham');
INSERT INTO Grounds VALUES ('County Ground','England','Taunton');
INSERT INTO Grounds VALUES ('Yorkshire','England','Leeds');
INSERT INTO Grounds VALUES ('Rose Bowl','England','Southampton');
INSERT INTO Grounds VALUES ('The Oval','England','London');
INSERT INTO Grounds VALUES ('Edgbaston','England','Birmingham');
INSERT INTO Grounds VALUES ('Cardiff Wales Stadium','England','Cardiff');