SET FOREIGN_KEY_CHECKS = 0;

INSERT INTO Matches VALUES (1,'The Oval');
INSERT INTO Matches VALUES (2,'Trent Bridge');
INSERT INTO Matches VALUES (3,'Cardiff Wales Stadium');
INSERT INTO Matches VALUES (4,'Bristol County Ground');
INSERT INTO Matches VALUES (5,'The Oval');
INSERT INTO Matches VALUES (6,'Trent Bridge');
INSERT INTO Matches VALUES (7,'Cardiff Wales Stadium');
INSERT INTO Matches VALUES (8,'Rose Bowl');
INSERT INTO Matches VALUES (9,'The Oval');
INSERT INTO Matches VALUES (10,'Trent Bridge');
INSERT INTO Matches VALUES (11,'Bristol County Ground');
INSERT INTO Matches VALUES (12,'Cardiff Wales Stadium');
INSERT INTO Matches VALUES (13,'County Ground');
INSERT INTO Matches VALUES (14,'The Oval');
INSERT INTO Matches VALUES (15,'Rose Bowl');
INSERT INTO Matches VALUES (16,'Bristol County Ground');
INSERT INTO Matches VALUES (17,'County Ground');
INSERT INTO Matches VALUES (18,'Trent Bridge');
INSERT INTO Matches VALUES (19,'Rose Bowl');
INSERT INTO Matches VALUES (20,'The Oval');
INSERT INTO Matches VALUES (21,'Cardiff Wales Stadium');
INSERT INTO Matches VALUES (22,'Old Trafford');
INSERT INTO Matches VALUES (23,'County Ground');
INSERT INTO Matches VALUES (24,'Old Trafford');
INSERT INTO Matches VALUES (25,'Edgbaston');
INSERT INTO Matches VALUES (26,'Trent Bridge');
INSERT INTO Matches VALUES (27,'Yorkshire');
INSERT INTO Matches VALUES (28,'Rose Bowl');
INSERT INTO Matches VALUES (29,'Old Trafford');
INSERT INTO Matches VALUES (30,"Lord's");
INSERT INTO Matches VALUES (31,'Rose Bowl');
INSERT INTO Matches VALUES (32,"Lord's");
INSERT INTO Matches VALUES (33,'Edgbaston');
INSERT INTO Matches VALUES (34,'Old Trafford');
INSERT INTO Matches VALUES (35,'Riverside Ground');
INSERT INTO Matches VALUES (36,'Yorkshire');
INSERT INTO Matches VALUES (37,"Lord's");
INSERT INTO Matches VALUES (38,'Edgbaston');
INSERT INTO Matches VALUES (39,'Riverside Ground');
INSERT INTO Matches VALUES (40,'Edgbaston');
INSERT INTO Matches VALUES (41,'Riverside Ground');
INSERT INTO Matches VALUES (42,'Yorkshire');
INSERT INTO Matches VALUES (43,"Lord's");
INSERT INTO Matches VALUES (44,'Yorkshire');
INSERT INTO Matches VALUES (45,'Old Trafford');
INSERT INTO Matches VALUES (46,'Old Trafford');
INSERT INTO Matches VALUES (47,'Edgbaston');
INSERT INTO Matches VALUES (48,"Lord's");