SET FOREIGN_KEY_CHECKS = 0;

INSERT INTO Squad_Members(`Player ID`,`Squad ID`,`Name`) VALUES (1,1,'RG Sharma');
INSERT INTO Squad_Members(`Player ID`,`Squad ID`,`Name`) VALUES (2,2,'DA Warner');
INSERT INTO Squad_Members(`Player ID`,`Squad ID`,`Name`) VALUES (3,8,'Shakib Al Hasan');
INSERT INTO Squad_Members(`Player ID`,`Squad ID`,`Name`) VALUES (4,4,'KS Williamson');
INSERT INTO Squad_Members(`Player ID`,`Squad ID`,`Name`) VALUES (5,3,'JE Root');
INSERT INTO Squad_Members(`Player ID`,`Squad ID`,`Name`) VALUES (6,3,'JM Bairstow');
INSERT INTO Squad_Members(`Player ID`,`Squad ID`,`Name`) VALUES (7,2,'AJ Finch');
INSERT INTO Squad_Members(`Player ID`,`Squad ID`,`Name`) VALUES (8,5,'Babar Azam');
INSERT INTO Squad_Members(`Player ID`,`Squad ID`,`Name`) VALUES (9,3,'BA Stokes');
INSERT INTO Squad_Members(`Player ID`,`Squad ID`,`Name`) VALUES (10,3,'JJ Roy');
INSERT INTO Squad_Members(`Player ID`,`Squad ID`,`Name`) VALUES (11,1,'V Kohli');
INSERT INTO Squad_Members(`Player ID`,`Squad ID`,`Name`) VALUES (12,7,'F du Plessis');
INSERT INTO Squad_Members(`Player ID`,`Squad ID`,`Name`) VALUES (13,2,'SPD Smith');
INSERT INTO Squad_Members(`Player ID`,`Squad ID`,`Name`) VALUES (14,2,'AT Carey');
INSERT INTO Squad_Members(`Player ID`,`Squad ID`,`Name`) VALUES (15,3,'EJG Morgan');
INSERT INTO Squad_Members(`Player ID`,`Squad ID`,`Name`) VALUES (16,8,'Mushfiqur Rahim');
INSERT INTO Squad_Members(`Player ID`,`Squad ID`,`Name`) VALUES (17,9,'N Pooran');
INSERT INTO Squad_Members(`Player ID`,`Squad ID`,`Name`) VALUES (18,1,'KL Rahul');
INSERT INTO Squad_Members(`Player ID`,`Squad ID`,`Name`) VALUES (19,4,'LRPL Taylor');
INSERT INTO Squad_Members(`Player ID`,`Squad ID`,`Name`) VALUES (20,2,'UT Khawaja');
INSERT INTO Squad_Members(`Player ID`,`Squad ID`,`Name`) VALUES (21,3,'JC Buttler');
INSERT INTO Squad_Members(`Player ID`,`Squad ID`,`Name`) VALUES (22,7,'HE van der Dussen');
INSERT INTO Squad_Members(`Player ID`,`Squad ID`,`Name`) VALUES (23,5,'Imam-ul-Haq');
INSERT INTO Squad_Members(`Player ID`,`Squad ID`,`Name`) VALUES (24,7,'Q de Kock');
INSERT INTO Squad_Members(`Player ID`,`Squad ID`,`Name`) VALUES (25,2,'MA Starc');
INSERT INTO Squad_Members(`Player ID`,`Squad ID`,`Name`) VALUES (26,4,'LH Ferguson');
INSERT INTO Squad_Members(`Player ID`,`Squad ID`,`Name`) VALUES (27,3,'JC Archer');
INSERT INTO Squad_Members(`Player ID`,`Squad ID`,`Name`) VALUES (28,8,'Mustafizur Rahman');
INSERT INTO Squad_Members(`Player ID`,`Squad ID`,`Name`) VALUES (29,1,'JJ Bumrah');
INSERT INTO Squad_Members(`Player ID`,`Squad ID`,`Name`) VALUES (30,3,'MA Wood');
INSERT INTO Squad_Members(`Player ID`,`Squad ID`,`Name`) VALUES (31,5,'Mohammad Amir');
INSERT INTO Squad_Members(`Player ID`,`Squad ID`,`Name`) VALUES (32,4,'TA Boult');
INSERT INTO Squad_Members(`Player ID`,`Squad ID`,`Name`) VALUES (33,5,'Shaheen Shah Afridi');
INSERT INTO Squad_Members(`Player ID`,`Squad ID`,`Name`) VALUES (34,3,'CR Woakes');
INSERT INTO Squad_Members(`Player ID`,`Squad ID`,`Name`) VALUES (35,4,'JDS Neesham');
INSERT INTO Squad_Members(`Player ID`,`Squad ID`,`Name`) VALUES (36,1,'Mohammed Shami');
INSERT INTO Squad_Members(`Player ID`,`Squad ID`,`Name`) VALUES (37,4.'MJ Henry');
INSERT INTO Squad_Members(`Player ID`,`Squad ID`,`Name`) VALUES (38,2,'PJ Cummins');
INSERT INTO Squad_Members(`Player ID`,`Squad ID`,`Name`) VALUES (39,7,'CH Morris');
INSERT INTO Squad_Members(`Player ID`,`Squad ID`,`Name`) VALUES (40,6,'SL Malinga');
INSERT INTO Squad_Members(`Player ID`,`Squad ID`,`Name`) VALUES (41,8,'Mohammad Saifuddin');
INSERT INTO Squad_Members(`Player ID`,`Squad ID`,`Name`) VALUES (42,9,'SS Cottrell');
INSERT INTO Squad_Members(`Player ID`,`Squad ID`,`Name`) VALUES (43,1,'YS Chahal');
INSERT INTO Squad_Members(`Player ID`,`Squad ID`,`Name`) VALUES (44,3,'LE Plunkett');
INSERT INTO Squad_Members(`Player ID`,`Squad ID`,`Name`) VALUES (45,7,'AL Phehlukwayo');
INSERT INTO Squad_Members(`Player ID`,`Squad ID`,`Name`) VALUES (46,7,'Imran Tahir');
INSERT INTO Squad_Members(`Player ID`,`Squad ID`,`Name`) VALUES (47,7,'K Rabada');
INSERT INTO Squad_Members(`Player ID`,`Squad ID`,`Name`) VALUES (48,5,'Wahab Riaz');
INSERT INTO Squad_Members(`Player ID`,`Squad ID`,`Name`) VALUES (49,3,'AU Rashid');
INSERT INTO Squad_Members(`Player ID`,`Squad ID`,`Name`) VALUES (50,1,'B Kumar');
INSERT INTO Squad_Members(`Player ID`,`Squad ID`,`Name`) VALUES (51,10,'Mohammad Nabi');
INSERT INTO Squad_Members(`Player ID`,`Squad ID`,`Name`) VALUES (52,1,'HH Pandya');