SET FOREIGN_KEY_CHECKS = 0;

INSERT INTO Statistics VALUES (1, 'RG Sharma', 9);
INSERT INTO Statistics VALUES (2, 'DA Warner', 10);
INSERT INTO Statistics VALUES (3, 'Shakib Al Hasan', 8);
INSERT INTO Statistics VALUES (4, 'KS Williamson', 10);
INSERT INTO Statistics VALUES (5, 'Joe Root', 11);
INSERT INTO Statistics VALUES (6, 'JM Bairstow', 11);
INSERT INTO Statistics VALUES (7, 'AJ Finch', 10);
INSERT INTO Statistics VALUES (8, 'Babar Azam', 8);
INSERT INTO Statistics VALUES (9, 'BA Stokes', 11);
INSERT INTO Statistics VALUES (10, 'JJ Roy', 8);
INSERT INTO Statistics VALUES (11, 'V Kohli', 9);
INSERT INTO Statistics VALUES (12, 'F du Plessis', 9);
INSERT INTO Statistics VALUES (13, 'SPD Smith', 10);
INSERT INTO Statistics VALUES (14, 'AT Carey', 10);
INSERT INTO Statistics VALUES (15, 'EJG Morgan', 11);
INSERT INTO Statistics VALUES (16, 'Mushifiqur Rahim', 8);
INSERT INTO Statistics VALUES (17, 'N Pooran', 9);
INSERT INTO Statistics VALUES (18, 'KL Rahul', 9);
INSERT INTO Statistics VALUES (19, 'LRPL Taylor', 10);
INSERT INTO Statistics VALUES (20, 'UT Khawaja', 9);
INSERT INTO Statistics VALUES (21, 'JC Buttler', 11);
INSERT INTO Statistics VALUES (22, 'HE van der Dussen', 9);
INSERT INTO Statistics VALUES (23, 'Imam-ul-Haq', 8);
INSERT INTO Statistics VALUES (24, 'Q de kock', 9);
INSERT INTO Statistics VALUES (25, 'MA Starc', 10);
INSERT INTO Statistics VALUES (26, 'LH Ferguson', 9);
INSERT INTO Statistics VALUES (27, 'JC Archer', 11);
INSERT INTO Statistics VALUES (28, 'Mustafizur Rahman', 8);
INSERT INTO Statistics VALUES (29, 'JJ Bumrah', 9);
INSERT INTO Statistics VALUES (30, 'MA Wood', 10);
INSERT INTO Statistics VALUES (31, 'Mohammad Amir', 8);
INSERT INTO Statistics VALUES (32, 'TA Boult', 10);
INSERT INTO Statistics VALUES (33, 'Shaheen Shah Afridi', 5);
INSERT INTO Statistics VALUES (34, 'CR Woakes', 11);
INSERT INTO Statistics VALUES (35, 'JDS Neesham', 10);
INSERT INTO Statistics VALUES (36, 'Mohammed Shami', 4);
INSERT INTO Statistics VALUES (37, 'MJ Henry', 9);
INSERT INTO Statistics VALUES (38, 'PJ Cummins', 10);
INSERT INTO Statistics VALUES (39, 'CH Morris', 8);
INSERT INTO Statistics VALUES (40, 'SL Malinga', 7);
INSERT INTO Statistics VALUES (41, 'Mohammad Saifuddin', 7);
INSERT INTO Statistics VALUES (42, 'SS Cottrell', 9);
INSERT INTO Statistics VALUES (43, 'YS Chahal', 8);
INSERT INTO Statistics VALUES (44, 'LE Plunkett', 7);
INSERT INTO Statistics VALUES (45, 'AL Phehlukwayo', 9);
INSERT INTO Statistics VALUES (46, 'Imran Tahir', 9);
INSERT INTO Statistics VALUES (47, 'K Rabada', 8);
INSERT INTO Statistics VALUES (48, 'Wahab Riaz', 8);
INSERT INTO Statistics VALUES (49, 'AU Rashid', 11);